- index.html
- js/main.js
> Adds mandrill to email form TEMPORARY

- index.html
Adds a line on how we're open source into the main page. Also fixes a small typo.
> Adds copy on open source

- index.html
- main.css
Implements: https://github.com/dwyl/dwyl.github.io/issues/9
Please review, discuss and/or merge. thanks
> send email (via mandril) to people who are interested in using dwyl

- main.css
> Fix issue of #features overflowing into #say-hello

- index.html
Generated via @mrzmyr 's [head-generator](http://mrzmyr.github.io/head-generator/).
Done to promote SEO for better discoverability and for an overall better experience. 😀
Much better!
> Improve head content

- index.html
Now it can do some basic form validations and be submitted by the Enter key.
> keep the default behavior of the form for a better web

- index.html
- package.json
+ update copy to be broader (less MVP-focussed fixes #79)
+ fixes https://github.com/dwyl/dwyl.github.io/issues/81
> update version of hapi to 12.1.0 (latest) 

- index.html
see: https://github.com/dwyl/dwyl.github.io/issues/84
> comment out the top nav until the scroll issue gets resolved

- css/dwyl.css
- index.html
Wasn't sure if 'anchor' was a class name consistent with the style guide. Let me know if not :)
> fixed anchor div positioning

- index.html
As per the title, a super simple PR to reverse #85 now anchoring is fixed.
> Adds nav back in as anchoring is now fixed

- css/dwyl.css
- index.html
Required by the coop bank for our application to change banks. Temporary change.
> A temporary addition of company address

- css/dwyl.css
This PR fixes the problem with firefox and the nav bar.
It also means that there is no transition animation with the nav bar (which personally I wasn't the biggest fan of).
> Temp fix for firefox nav bug #120

- css/dwyl.css
Fixed a margin problem on small phone screens.
Spash image size corrected on iphones.
> Fix iphone background bug

- css/dwyl.css
- views/team.html
**Ready to merge, will add anything else to further PRs**
Includes:
+ Adjusted spacing in CSS (felt a little like we were trying to fill up the page and there was *way* too much whitespace between people on mobile)
+ Added suggested titles (pretty uniform, I'm not thrilled about it, but better than none at this stage!)
> Adding roles to team page

- package.json
- views/index.html
- views/values.html
> make w3c happy

- .eslintignore
- package.json
- readme.md
- routes.js
- server.js
- test/members.spec.js
Adding tests and pre-commit hooks to ensure all of the images exist
Adding goodparts code style and goodparts badge
> Linting+tests

- members.json
Links to
https://github.com/dwyl/dwyl.github.io/pull/191
Alumni > Alumna
> alumni to alumna #191

- views/index.html
> Office Address Update #203

- views/index.html
> Spelling Correction

- .travis.yml
- package.json
fixes https://github.com/dwyl/dwyl-site/issues/231
> update dependencies to latest versions (Hapi 16.1.0 >> 16.3.0) 

- views/index.html
Services Updates
https://github.com/dwyl/print-me/issues/25#issuecomment-307750296
> Services Updates

- redesign/portfolio.html
- Adds Portfolio title
- Sets page on white background
- Uses the portfolio boxes from the landing page
#281
> Portfolio, #281

- redesign/blog.html
- redesign/community.html
- redesign/cs-emf.html
- redesign/index.html
- redesign/portfolio.html
- views/index.html
#293 Styling tweaks to the contact us section success message
#291 Adds urls to EMF case study page
#281 Aligns Portfolio title with boxes
> Small fixes

- redesign/blog.html
- redesign/community.html
- redesign/cs-emf.html
- redesign/index.html
- redesign/portfolio.html
> #222 Adds tag manager

- redesign/blog.html
- redesign/community.html
- redesign/cs-emf.html
- redesign/css/dwyl.css
- redesign/index.html
- redesign/portfolio.html
Adds thicker font weight option for Montserrat and then resizes/positions pages accordingly #294 
Removes any no longer needed custom classes.
> #294 Font weight

- redesign/app.html
- redesign/css/dwyl.css
- redesign/js/app_google_form_handler.js
#309 Creates functioning form for the app page
> #309 Creates functioning form for the app page

- redesign/app.html
- redesign/blog.html
- redesign/community.html
- redesign/cs-emf.html
- redesign/css/dwyl.css
- redesign/index.html
- redesign/portfolio.html
- redesign/team.html
- redesign/values.html
#327 Fixes broken links across multiple pages
#326 #330 Updates the address in footer and the contact section
#332 Changes job title on team page
> Small tweaks

- redesign/app.html
- redesign/blog.html
- redesign/community.html
- redesign/cs-emf.html
- redesign/index.html
- redesign/portfolio.html
- redesign/team.html
- redesign/values.html
Adds some tiny tweaks to alt text
#347
> tiny tweaks to alt text

- redesign/blog.html
- redesign/careers.html
- redesign/welcome.html
#301 creates individual blog post page
- comments out other blog post layout so this is not lost for when there are multiple posts
- gives lorem ipsum text for now for first blog
- Intends to move blog post into a blog folder but was losing styling upon doing this - bug
#334 creates careers page (copy only, design just interpreted at this stage)
> Blog posts

- app.html
- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- redesign/careers.html
- redesign/case-studies/ellen-macarthur-foundation/CE100.html
- redesign/case-studies/inclusive-classrooms/skills-wheel.html
- redesign/case-studies/science-museum-group/online-collections.html
- redesign/values.html
- redesign/welcome.html
- team.html
- values.html
Removes keyword tag, as well as pointless (they are the default) 'follow' and 'index' tags #343
> Remove keyword meta tags

- index.html
Adds padding and fixes responsiveness on the homepage #358
> Improves homepage responsiveness

- css/dwyl.css
- team.html
Displays three team members at medium resolution displays #367
> Adds an extra 30% breakpoint to the team profiles

- blog.html
- blog/2017/september/welcome.html
Fixes responsiveness on the blog page, as well as sorting out the top nav, footer and contact section of the nested blog page (welcome.html).
#379
> Blog page responsiveness

- img/manifest.json
changes `name` attribute in manifest.json from "App" to "dwyl".
fix #387
>  manifest.json fix

- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
Adds padding to the contact form anchor tag when on mobile #372
> fixes contact form padding (mobile)

- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- css/dwyl.css
- index.html
- js/app_google_form_handler.js
- portfolio.html
- team.html
- time-app.html
- values.html
Ignores some warnings but fixes all the errors.
#14
> Addresses all pa11y accessibility errors

- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
Adds padding to the title, adds max width and aligns text sections at all widths.
#397
> Career page changes

- 404.html
- blog.html
- blog/2017/september/welcome.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
> Fixes contact anchor links

- css/dwyl.css
- portfolio.html
Replaces the popular repo images with html/css
#401
> Adds popular repo cards

- 404.html
- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
adds new google tag manager snippets to all pages #222
> Add tag manager snippets

- README.md
Adds cloudflare setup instructions to the readme #426
> adds cloudflare documentation

- team.html
Further updates required, but most immediate update in this PR.
@rub1e @nelsonic Whichever one of you gets to this first, please review & merge 👍
> Updates team page

- portfolio.html
> Adds note saying more case studies on their way - #441

- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/science-museum-group/online-collections.html
> Portfolio links

- 404.html
- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/science-museum-group/online-collections.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
+ updates address to space 4 in footer and on contact form 
+ updates copyright date
#454 #453
> Address and copyright update

- portfolio.html
As per #464, this fixes the broken link (my bad 🙈) in portfolio.html
> Fixes broken healthlocker link

- community.html
Change link to Join Us to https://github.com/dwyl/start-here/issues/143
Ref #471 
I can't run `crouton` at the moment so I can't check this PR right now - I just did it with the Web Editor
> Change link to Join Us

- 404.html
- blog.html
- blog/2017/september/welcome.html
- careers.html
- case-studies/city-university/quodl.html
- case-studies/ellen-macarthur-foundation/CE100.html
- case-studies/inclusive-classrooms/skills-wheel.html
- case-studies/nhs-england/good-thinking.html
- case-studies/nhs-south-london-and-maudsley/healthlocker.html
- case-studies/oxford-abstracts/oxford-abstracts.html
- case-studies/science-museum-group/online-collections.html
- case-studies/thomas-cook/tc-serverless.html
- community.html
- index.html
- portfolio.html
- team.html
- time-app.html
- values.html
Ref https://github.com/dwyl/hq/issues/528 - updating the address to Fonthill Road
Ref https://github.com/dwyl/dwyl-site/issues/473 - updating Copyright date to 2019
> 2019 update address

- 404.html
> Add remedy section on 404 page

- css/dwyl.css
- portfolio.html
+ [x] Improve link contrast for issue https://github.com/dwyl/dwyl-site/issues/479
> Updated colors for a11y. Fixes #479.
